### ISSUE TITLE
Typeorm Package Failing

### ISSUE THREAD

**Issue by DEVSOG12** [BuildForSDGCohort2/Team-Techbuzs-Backend#2]
I'm on IT @DEVSOG12

**Comment by ISI-Gbemi** [comment]
> I'm on IT @DEVSOG12

Yh nice
Anything else to do rn

**Comment by ISI-Gbemi** [comment]
Yh got it

**Comment by ISI-Gbemi** [comment]
On it right now

**Comment by DEVSOG12** [comment]
I'm almost done! Setting up more Workflow on Github Projects

**Comment by DEVSOG12** [comment]
Done. Everything Works Fine!!

Closing it.

Thanks @dev4larin
